apiVersion: kubedb.com/v1alpha1
kind: Postgres
metadata:
  name: "{{ .Values.name }}"
spec:
  version: "11.2"
  databaseSecret:
    secretName: channel-db-auth
  storageType: Durable
  storage:
    storageClassName: {{ required "storageClassName is required" .Values.global.defaultStorageClassName }}
    accessModes:
      - ReadWriteOnce
    resources:
      requests:
        storage: 3Gi
  podTemplate:
    metadata:
      labels:
        app: postgres
  init:
    scriptSource:
      configMap:
        name: {{ .Values.name }}-init
  terminationPolicy: Pause