apiVersion: v1
kind: Service
metadata:
  name: "{{ .Values.name }}"
spec:
  type: "{{ .Values.type }}"
  selector:
    app: "{{ .Values.name }}"
  ports:
    - name: http
      port: {{ .Values.servicePort }}
      targetPort: {{ .Values.containerPort }}
