apiVersion: apps/v1
kind: Deployment
metadata:
  name: "user-service"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: "user-service"
  template:
    metadata:
      labels:
        app: "user-service"
    spec:
      containers:
        - name: "user-service"
          image: "user-service:{{ .Values.global.services.user_service.tag }}"
          imagePullPolicy: "Never"
          readinessProbe:
            initialDelaySeconds: 5
            periodSeconds: 15
            httpGet:
              path: "/health"
              port: 8080
          livenessProbe:
            initialDelaySeconds: 15
            periodSeconds: 5
            httpGet:
              path: "/health"
              port: 8080
          env:
            - name: DB_HOST
              value: "user-db"
            - name: DB_PORT
              value: "5432"
            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: "user-db-auth"
                  key: "POSTGRES_USER"
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: "user-db-auth"
                  key: "POSTGRES_PASSWORD"
            - name: DB_NAME
              value: "user-db"
          ports:
            - containerPort: 8080
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "128Mi"
              cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
  name: "user-service"
spec:
  type: "ClusterIP"
  selector:
    app: "user-service"
  ports:
    - name: http
      port: 8080
      targetPort: 8080
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: user-service
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  rules:
  - http:
      paths:
      - path: api/user(/|$)(.*)
        pathType: Prefix
        backend:
          service:
            name: user-service
            port:
              number: 8080